### PR TITLE
[website] make emotions more neutral

### PR DESCRIPTION
**Pull request by kbrandwijk**
# Why

I noticed a few negative outliers in the range of possible emotions a Snack can have.

# How

Removed a few of the ones that can invoke negative associations.

# Test Plan

Didn't test. It's a list of strings...

### CODE REVIEW

**Comment by kbrandwijk** [comment]
87x75 (6525) down to 73x75 (5475) isn't huge, but definitely not negligible. That being said, I think the number of possibilities is still large enough though, they don't need to be globally unique, right?

**Comment by byCedric** [comment]
Unfortunately, they do need to be globally unique. So let's find something to bump it up to at least 6000+

We could add something boring like "weather" (`sunny`, `rainy`, `windy`) etc as additional set, that should boost it to the safe zone.

**Comment by byCedric** [comment]
Color seems like a good option too yeah

**Comment by byCedric** [comment]
Merging this in, but will add color.

**Pull request merged**
